### ISSUE TITLE
One of two same desktop display monitors returned: no valid output was received from brightness methods

### ISSUE THREAD

**Issue by Hermi-Mire** [Crozzers/screen_brightness_control#44] opened 2024-12-26 06:02 UTC
Hi,
Thanks for your wonderful project.

**Describe the bug**
Almost the same problem as #13 , tried to debug but got stuck somewhere. 

**To Reproduce**
```python
import screen_brightness_control as sbc

raw_monitors_list= sbc.list_monitors()

for i in raw_monitors_list:
    print(i)
    sbc.get_brightness(i)
```
Got:

```
AOC Generic Monitor
Traceback (most recent call last):
  File "D:\Hermi\Project\screen_brightness_control\test.py", line 8, in <module>
    sbc.get_brightness(i)
  File "D:\Hermi\Project\screen_brightness_control\screen_brightness_control\config.py", line 16, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Hermi\Project\screen_brightness_control\screen_brightness_control\__init__.py", line 55, in get_brightness
    result = __brightness(
             ^^^^^^^^^^^^^
  File "D:\Hermi\Project\screen_brightness_control\screen_brightness_control\__init__.py", line 755, in __brightness
    raise ScreenBrightnessError(msg)
screen_brightness_control.exceptions.ScreenBrightnessError: 
	no valid output was received from brightness methods
```

**Debug info**
My monitor info from `sbc.list_monitors_info()` , serial numbers and EDIDs omitted:
```
[{'name': 'AOC Generic Monitor', 'model': 'Generic Monitor', 'manufacturer': 'AOC', 'manufacturer_id': 'AOC', 
'uid': '772', 'method': <class 'screen_brightness_control.windows.VCP'>, 'index': 0}, 
{'name': 'AOC Generic Monitor', 'model': 'Generic Monitor', 'manufacturer': 'AOC', 'manufacturer_id': 'AOC', 
'uid': '20529', 'method': <class 'screen_brightness_control.windows.VCP'>, 'index': 1}]
```
It works for the second monitor with 'index': 1, but not for the monitor with 'index': 0

```
D:\Hermi\Project\screen_brightness_control> python -m screen_brightness_control -l
Display 0: AOC Generic Monitor
Display 1: AOC Generic Monitor
```
```
D:\Hermi\Project\screen_brightness_control> python -m screen_brightness_control -s 0
AOC Generic Monitor -> Failed
AOC Generic Monitor -> 0%
```
```
(Pdb) sbc.windows.VCP
<class 'screen_brightness_control.windows.VCP'>
(Pdb) sbc.windows.VCP.get_brightness(display=1)                          
[70]
(Pdb) sbc.windows.VCP.get_brightness(display=0) 
[]

```
**Environment**
screen_brightness_control --version 0.24.1
Python 3.12.4
Win11

The only difference I could find between these two monitors is that the first one is connected to the `Radeon RX550/550 Series`, while the second one is connected to the `Intel(R) UHD Graphics 730`. Let me know if you need anything else.

**Comment by Crozzers** [comment] 2024-12-26 10:54
> The only difference I could find between these two monitors is that the first one is connected to the `Radeon RX550/550 Series`, while the second one is connected to the `Intel(R) UHD Graphics 730`.

Interesting. If I was to guess at the cause, I'd say this would be the most likely source of issues. Is it possible to connect them both to the same graphics output and see if that makes a difference?
In the mean time I'll see if I can replicate that config and reproduce the bug

**Comment by Hermi-Mire** [comment] 2024-12-27 07:56
Hi,

Yeah, apart from the negligible refresh rate difference caused by the performance gap between the two graphics cards, I haven’t encountered any issues so far—until I wanted to automate brightness adjustment and found this repo :D. Perhaps I’ll need a docking station to solve this problem.

Here's the output:

```
================DEBUG INFO================
{'all_monitors': [{'get_brightness': [],
                   'global_index': 0,
                   'info': {
                            'index': 0,
                            'manufacturer': 'AOC',
                            'manufacturer_id': 'AOC',
                            'method': <class 'screen_brightness_control.windows.VCP'>,
                            'model': 'Generic Monitor',
                            'name': 'AOC Generic Monitor',
                            'uid': '772'},
                   'set_brightness': 'Traceback (most recent call last):\n'
                                     '  File '
                                     '"D:\\Hermi\\Project\\screen_brightness_control\\screen_brightness_control\\_debug.py", '
                                     'line 74, in info\n'
                                     '    brightness[0] if '
                                     'isinstance(brightness, list) else 100,\n'
                                     '    ~~~~~~~~~~^^^\n'
                                     'IndexError: list index out of range\n'},
                  {'get_brightness': [80],
                   'global_index': 1,
                   'info': {
                            'index': 1,
                            'manufacturer': 'AOC',
                            'manufacturer_id': 'AOC',
                            'method': <class 'screen_brightness_control.windows.VCP'>,
                            'model': 'Generic Monitor',
                            'name': 'AOC Generic Monitor',
                            'uid': '20529'},
                   'set_brightness': None}],
 'file': 'D:\\Hermi\\Project\\screen_brightness_control\\screen_brightness_control\\__init__.py',
 'filtered_monitors': [{
                        'index': 0,
                        'manufacturer': 'AOC',
                        'manufacturer_id': 'AOC',
                        'method': <class 'screen_brightness_control.windows.VCP'>,
                        'model': 'Generic Monitor',
                        'name': 'AOC Generic Monitor',
                        'uid': '772'},
                       {
                        'index': 1,
                        'manufacturer': 'AOC',
                        'manufacturer_id': 'AOC',
                        'method': <class 'screen_brightness_control.windows.VCP'>,
                        'model': 'Generic Monitor',
                        'name': 'AOC Generic Monitor',
                        'uid': '20529'}],
 'methods': [{'class': "<class 'screen_brightness_control.windows.WMI'>",
              'displays': [],
              'name': 'wmi'},
             {'class': "<class 'screen_brightness_control.windows.VCP'>",
              'displays': [{'global_index': 0, 'index': 0},
                           {'global_index': 1, 'index': 1}],
              'name': 'vcp'}],
 'platform': 'Windows',
 'version': '0.24.1',
 'windows': {'physical_monitor_handles': ['None', 'None'],
             'win32api_enum_display_device_ids': ['\\\\?\\DISPLAY#AOC2490#5&37a05138&0&UID772#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}',
                                                  '\\\\?\\DISPLAY#AOC2490#4&4b5f8c3&0&UID20529#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'],
             'wmi_monitor_id_output': [<_wmi_object: b'\\\\root\\wmi:WmiMonitorID.InstanceName="DISPLAY\\\\AOC2490\\\\5&37a05138&0&UID772_0"'>,
                                       <_wmi_object: b'\\\\root\\wmi:WmiMonitorID.InstanceName="DISPLAY\\\\AOC2490\\\\4&4b5f8c3&0&UID20529_0"'>]}}
===================LOGS===================
DEBUG:screen_brightness_control._debug.info:gathering list of all monitors
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:'windows_monitors_info_raw' not present in cache
WARNING:screen_brightness_control.windows:get_display_info: failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:cache set 'windows_monitors_info_raw', expires=1
DEBUG:screen_brightness_control._debug.info:filtering the list of monitors
DEBUG:screen_brightness_control._debug.info:get_brightness for monitor VCP:0
WARNING:screen_brightness_control.windows.VCP:failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:'vcp_brightness_0' not present in cache
ERROR:screen_brightness_control.windows.VCP:failed to get VCP feature reply for display:0 after 49 tries
DEBUG:screen_brightness_control._debug.info:set_brightness for monitor VCP:0
DEBUG:screen_brightness_control._debug.info:get_brightness for monitor VCP:1
WARNING:screen_brightness_control.windows.VCP:failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:delete expired key windows_monitors_info_raw
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:'vcp_brightness_1' not present in cache
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:cache set 'vcp_brightness_1', expires=0.1
DEBUG:screen_brightness_control._debug.info:set_brightness for monitor VCP:1
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:delete keys startswith='vcp_brightness_'
WARNING:screen_brightness_control.windows.VCP:failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>
DEBUG:screen_brightness_control._debug.info:getting display info for method: wmi
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:'windows_monitors_info_raw' not present in cache
WARNING:screen_brightness_control.windows:get_display_info: failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>
DEBUG:screen_brightness_control.helpers.__Cache_2135860068480:cache set 'windows_monitors_info_raw', expires=1
DEBUG:screen_brightness_control._debug.info:getting display info for method: vcp
DEBUG:screen_brightness_control._debug.info:windows specific debug info
WARNING:screen_brightness_control.windows.VCP:failed to gather list of laptop displays - x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>

```

**Comment by Crozzers** [comment] 2024-12-27 14:56
The debug info indicates that both monitors are present and return handles that can be used, but for some reason the first monitor is not responding to the get brightness VCP command. This usually means one of a few things:
- The monitor doesn't support VCP or DDC/CI (unlikely as it seems to be the same model as the working one)
- The monitor doesn't have VCP or DDC/CI or MCCS enabled

Try poking around in your monitor's OSD and see if there's a setting for VCP, MCCS or DDC/CI.
Could you also run this code which should detail what VCP capabilities each monitor supports, if any?:
```python
import ctypes
from ctypes import windll
from ctypes.wintypes import DWORD

from screen_brightness_control.windows import VCP

for index, handle in enumerate(VCP.iter_physical_monitors()):
    print("Handle", index)
    str_len = DWORD()
    if not windll.dxva2.GetCapabilitiesStringLength(handle, ctypes.byref(str_len)):
        print("No str len")
        continue
    cap_str = (ctypes.c_char * str_len.value)()
    if not windll.dxva2.CapabilitiesRequestAndCapabilitiesReply(
        handle, cap_str, str_len
    ):
        print("No cap str")
        continue
    print(cap_str.value.decode("ASCII"))
```

**Comment by Hermi-Mire** [comment] 2024-12-30 02:15
Hi,

I have checked the OSD and I'm sure the DDC/CI is on. 

Here's the output:
```
Handle 0
No str len
Handle 1
(vcp(02 04 05 08 10 12 14(01 05 06 08 0B) 16 18 1A 52 60(01 0F 11 12 ) 62 86(02 05) C8 C9 CC(01 02 03 04 05 06 07 09 0A 0B 0D 0E 12 14 16 1E) B6 DF D6(01 04) F8)prot(monitor)type(LCD)cmds(01 02 03 07 0C F3)mccs_ver(2.2)asset_eep(64)mpu_ver(001)model(Q2490PXQ)mswhql(1))

```

**Comment by Crozzers** [comment] 2024-12-30 13:05
So the monitor is not responding to any DDC signals. If it is the exact same make and model as the other monitor, I'd say there's probably a hardware problem somewhere else in the chain. Out of curiosity, what CPU/MOBO are you using?

If monitor 0 is plugged into the integrated graphics, try moving it to the dedicated GPU and vice versa. See if that makes a difference. If the monitor doesn't work on either then there's something wrong with the display, or maybe the cable connecting the display to the PC

**Comment by Hermi-Mire** [comment] 2024-12-30 13:58
The CPU is i5-12400. I have switched both the HDMI cable and the graphics ,and have determined that it works properly only when connected to the monitor that is linked to the integrated graphics.

**Comment by Crozzers** [comment] 2024-12-30 14:24
In that case, this is an issue with the card/driver and there's not much I can do. Looking in AMD forums I can see similar threads of [not being able to use DDC/CI on RX500 series cards](https://community.amd.com/t5/pc-drivers-software/ddc-ci-support/m-p/335967) and also [RX5000 series cards](https://community.amd.com/t5/pc-drivers-software/ddc-ci-not-working-with-displayport-on-amd-radeon-5700-xt/td-p/406350), so maybe this was an AMD issue for a while. Seems to be fixed on newer generations.

I've poked around in the Adrenalin control panel and can't see any options relating to DDC/CI, so the only other thing I can think of is updating the drivers and seeing if that makes a difference. Otherwise, this isn't a problem I can solve

**Closed by Crozzers** 2024-12-30 14:24 UTC
Labels: bug
